name: reserva_canchas
description: Aplicación para reservar canchas sintéticas.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.0.5
  table_calendar: ^3.0.9
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  http: ^1.3.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  flutter_staggered_animations: ^1.1.1
  flutter_animate: ^4.3.0  
  google_fonts: ^6.1.0   
  fl_chart: ^0.67.0
  pdf: ^3.10.6
  csv: ^5.1.1
  cloud_functions: ^5.5.0
  crypto: ^3.0.5
  url_launcher: ^6.2.2
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img1.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/cancha11.jpg
    - assets/cancha2.jpg
    - assets/cancha3.jpg
    - assets/cancha4.jpg
    - assets/img1.png
    - assets/fondo.jpg
    - assets/fondo2.jpg
    - assets/cancha_demo.png
