// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLzBcnexpfCtmUkmG61r9MQ6_h2Uu-UKM',
    appId: '1:201739490840:web:d2159a208f44b7ce6a156d',
    messagingSenderId: '201739490840',
    projectId: 'canchas-la-jugada',
    authDomain: 'canchas-la-jugada.firebaseapp.com',
    storageBucket: 'canchas-la-jugada.firebasestorage.app',
    measurementId: 'G-YTREJN95RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBusN_n3CDJwBFTsl38OA3YYeNhr-TOleo',
    appId: '1:201739490840:android:084fb44cd89806a16a156d',
    messagingSenderId: '201739490840',
    projectId: 'canchas-la-jugada',
    storageBucket: 'canchas-la-jugada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFuQ_OAqh4OCedS2bKw8YBPolQA8asCV8',
    appId: '1:201739490840:ios:1ea7a5ccd33e36286a156d',
    messagingSenderId: '201739490840',
    projectId: 'canchas-la-jugada',
    storageBucket: 'canchas-la-jugada.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

}