// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD57tk7priOgb45wXC7YJNqn9NZTTH0jtw',
    appId: '1:185214677471:web:fa3326285cba36efff946a',
    messagingSenderId: '185214677471',
    projectId: 'proyecto-20bae',
    authDomain: 'proyecto-20bae.firebaseapp.com',
    storageBucket: 'proyecto-20bae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuDGMwPMY-wkYOqYhkaJ2zkVT4GNbn75Y',
    appId: '1:185214677471:android:67e1cc2030b5d7e6ff946a',
    messagingSenderId: '185214677471',
    projectId: 'proyecto-20bae',
    storageBucket: 'proyecto-20bae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMUp3P8rKkgh5aWtjKXZosWJ5YjN_5Erg',
    appId: '1:185214677471:ios:8149b93a736be037ff946a',
    messagingSenderId: '185214677471',
    projectId: 'proyecto-20bae',
    storageBucket: 'proyecto-20bae.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD57tk7priOgb45wXC7YJNqn9NZTTH0jtw',
    appId: '1:185214677471:web:e459f2f38448b6afff946a',
    messagingSenderId: '185214677471',
    projectId: 'proyecto-20bae',
    authDomain: 'proyecto-20bae.firebaseapp.com',
    storageBucket: 'proyecto-20bae.firebasestorage.app',
  );
}
